/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ChatNameImport } from './routes/$chatName'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ChatNameRoute = ChatNameImport.update({
  path: '/$chatName',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$chatName': {
      id: '/$chatName'
      path: '/$chatName'
      fullPath: '/$chatName'
      preLoaderRoute: typeof ChatNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$chatName': typeof ChatNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$chatName': typeof ChatNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$chatName': typeof ChatNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$chatName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$chatName'
  id: '__root__' | '/' | '/$chatName'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatNameRoute: typeof ChatNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatNameRoute: ChatNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$chatName"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$chatName": {
      "filePath": "$chatName.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
